name: project8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  buttons_tabbar: ^1.3.13
  flutter:
    sdk: flutter
  otp_timer_button: ^1.1.1
  pinput: ^5.0.0
  flutter_image_slideshow: ^0.1.6
  font_awesome_flutter: ^10.7.0
  flutter_floating_bottom_bar: ^1.2.1+1
  flutter_bloc: ^8.1.6
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  get_it: ^8.0.0
  dotenv: ^4.2.0
  bloc: ^8.1.4
  meta: ^1.15.0
  onesignal_flutter: ^5.2.5
  url_launcher: ^6.3.0
  lottie: ^3.1.2
  easy_stepper: ^0.8.5+1
  rive: ^0.13.14
  http: ^1.2.2
  moyasar: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - 'assets/'
  - 'assets/images/'
  - 'assets/fonts/'
  - '.env'

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Average
      fonts:
        - asset: assets/fonts/Average-Regular.ttf