name: onze_coffee_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  moyasar: ^2.0.13
  readmore: ^3.0.0
  supabase_flutter: ^2.6.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  file_picker: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/logo/
    - assets/images/
    - assets/banner/
    - assets/product/
    - .env

  uses-material-design: true
