name: onze_coffee_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/logo/
    - assets/banner/
    - assets/product/
  uses-material-design: true
