/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'onze_cafe';
  static const String PLUGIN_VERSION = '0.1.0';
  static const String COFFEE_CUP = 'assets/coffee_cup.png';
  static const String BOX = 'assets/illustrations/box.png';
  static const String ILLUSTRATION_8 =
      'assets/illustrations/illustration_8.png';
}
