name: customer_app
description: "A new Flutter project."

publish_to: none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  get_storage: ^2.1.1
  pinput: ^5.0.0
  device_preview: ^1.2.0
  icons_plus: ^5.0.0
  intl: ^0.19.0
  dio: ^5.7.0
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  buttons_tabbar: ^1.3.13
  custom_radio_grouped_button: ^2.2.1
  flutter_stepindicator: ^0.0.2
  lottie: ^3.1.2
  moyasar: ^2.0.13
  onesignal_flutter: ^5.2.5
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/readme/
    - .env


  fonts:
    - family: Rosarivo
      fonts:
        - asset: assets/fonts/Rosarivo-Regular.ttf


    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

